language: java
jdk:
- oraclejdk8
script: mvn test package
deploy:
  provider: releases
  api_key:
    secure: DDCNP5/lcx9YWKienHuFU2+b/acibAKdIddGMXMBvperNzr8GmNDpyoSFiTGVDl2SDE86eZoDMvCCXbu2lBdKsy3LPZo4Gbqlom5GtcnMPy/88xEM95NHgBLYOAE5vRkDQbbuDtYO2U6rve00PL36QxrfeAryHu4P3M3CSixw24=
  file: "target/DNPakTool-1.0.3.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: vincentzhang96/DNPakTool
